apiVersion: v1
kind: Service
metadata:
  name: bhumika-frontend-svc
spec:
  selector:
    app: bhumika-frontend
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      name: frontend
