apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |
    input {
      file {
        path => "/usr/share/logstash/data/flask_app/app/flask_app.log" 
        start_position => "beginning"
        sincedb_path => "/dev/null" # disable sincedb to always read from the beginning
      }
    }

    filter {
      grok {
        match => { "message" => "%{TIMESTAMP_ISO8601:timestamp}\s+-\s+%{LOGLEVEL:loglevel}\s+-\s+%{GREEDYDATA:message}" }
      }
    }

    output {
      elasticsearch {
        hosts => ["elasticsearch:9200"]
        index => "flask-logs-%{+YYYY.MM.dd}"
      }
    }
