apiVersion: v1
kind: Service
metadata:
  name: mysql-t2i
  labels:
    app: mysql-t2i
spec:
  ports:
    - port: 3306
      name: mysql
  selector:
    app: mysql-t2i
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-t2i
  labels:
    app: mysql-t2i
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-t2i
  template:
    metadata:
      labels:
        app: mysql-t2i
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          ports:
            - containerPort: 3306
              name: mysql
